language: go

go: 1.10.x

install: skip

env:
  global:
      - CHANGED_DIRS="service1 service2"

jobs:
  include:
    - &test-stage
      stage: test
      env: SERVICE="service1" APP_ENV=test TEST_SUITE=php_functional_1 IGNORE=$(./ci/test.sh)
      # if: env(IGNORE) = 0
      script:
          - ./ci/test.sh

    - <<: *test-stage
      # if: env(IGNORE) = 0
      env: SERVICE="service1" APP_ENV=test TEST_SUITE=php_functional_2 IGNORE=$(./ci/test.sh)

    - <<: *test-stage
      # if: env(IGNORE) = 0
      env: SERVICE=service2 IGNORE=$(./ci/test.sh)

    - <<: *test-stage
      # if: env(IGNORE) = 0
      env: SERVICE="service3" SOME_OTHER_VAR="whatever" IGNORE=$(./ci/test.sh)
