language: go

go: 1.10.x

install: skip

env:
  - CHANGED_DIRS="service1\nservice2\n"

jobs:
  include:
    - &test-stage
      stage: test
      env: SERVICE="service1" APP_ENV=test TEST_SUITE=php_functional_1
      script:
          - ./ci/test.sh

    - <<: *test-stage
      env: SERVICE="service1" APP_ENV=test TEST_SUITE=php_functional_2

    - <<: *test-stage
      env: SERVICE=service2

    - <<: *test-stage
      env: SERVICE="service3" SOME_OTHER_VAR="whatever"

