language: go

go: 1.10.x

install:
  - git fetch origin master
  - echo "---$(./ci/services.sh)---"

env:
  global:
      # - CHANGED_DIRS=$(./ci/services.sh)
      # - CHANGED_DIRS=@ci/services.sh@@services/service3@@services/service4@
      - CHANGED_DIRS=@ci/services.sh@@ci/test.sh@@services/service3@@services/service4@

jobs:
  include:
    - &test-stage
      stage: test
      env: SERVICE="service1" APP_ENV=test TEST_SUITE=php_functional_1
      if: env(CHANGED_DIRS) =~ @services/service1@
      script:
          - ./ci/test.sh

    - <<: *test-stage
      if: env(CHANGED_DIRS) =~ @services/service1@
      env: SERVICE="service1" APP_ENV=test TEST_SUITE=php_functional_2

    - <<: *test-stage
      if: env(CHANGED_DIRS) =~ @services/service2@
      env: SERVICE=service2

    - <<: *test-stage
      if: env(CHANGED_DIRS) =~ @services/service3@
      env: SERVICE="service3" SOME_OTHER_VAR="whatever"

    - <<: *test-stage
      if: env(CHANGED_DIRS) =~ @services/service4@
      env: SERVICE="service4"
