language: go

go: 1.10.x

install: skip

# todo:
# - in single service branch make sure not other dirs were modified

jobs:
  include:
    # Pre flight checks
    - stage: validation
      if: NOT branch =~ ^srv- AND NOT branch =~ ^lib- AND NOT branch =~ ^multi- AND NOT branch = master
      script:
        - echo -e "\n\nILLEGAL BRANCH NAME $TRAVIS_BRANCH\nMust begin with srv- or lib- or multi-" && exit 1

    # Test libraries
    - &lib-test-stage
      stage: test libraries
      script:
        - COMPONENT_TYPE=lib ./ci/modified.sh || travis_terminate
        - COMPONENT_TYPE=lib ./ci/test.sh
      if: branch =~ ^lib-library1- OR branch =~ ^multi- OR branch = master
      env: COMPONENT_NAME=library1 TEST_SUITE=php_functional_1

    - <<: *lib-test-stage
      if: branch =~ ^lib-library2- OR branch =~ ^multi- OR branch = master
      env: COMPONENT_NAME=library2 TEST_SUITE=php_functional_2


    # Test services
    - &srv-test-stage
      stage: test services
      script:
        - COMPONENT_TYPE=srv ./ci/modified.sh || travis_terminate
        - BUILD_ENV=test COMPONENT_TYPE=srv ./ci/test.sh
      if: branch =~ ^srv-service1- OR branch =~ ^multi- OR branch = master
      env: COMPONENT_NAME=service1 TEST_SUITE=php_functional_1

    - <<: *srv-test-stage
      if: branch =~ ^srv-service1- OR branch =~ ^multi- OR branch = master
      env: COMPONENT_NAME=service1 TEST_SUITE=php_functional_2

    - <<: *srv-test-stage
      if: branch =~ ^srv-service2- OR branch =~ ^multi- OR branch = master
      env: COMPONENT_NAME=service2

    - <<: *srv-test-stage
      if: branch =~ ^srv-service3- OR branch =~ ^multi- OR branch = master
      env: COMPONENT_NAME=service3 SOME_OTHER_VAR=whatever

    - <<: *srv-test-stage
      if: branch =~ ^srv-service4- OR branch =~ ^multi- OR branch = master
      env: COMPONENT_NAME=service4 AA=1

    - <<: *srv-test-stage
      if: branch =~ ^srv-service4- OR branch =~ ^multi- OR branch = master
      env: COMPONENT_NAME=service4 BB=1

    # Dev image to be used for nobob and QA
    - &dev-deploy-stage
      stage: deploy
      script:
        - COMPONENT_TYPE=srv ./ci/modified.sh || travis_terminate
        - BUILD_ENV=dev ./ci/deploy.sh
      if: branch =~ ^srv-service1- OR branch =~ ^multi- OR branch = master
      env: COMPONENT_NAME=service1

    - <<: *dev-deploy-stage
      if: branch =~ ^srv-service2- OR branch =~ ^multi- OR branch = master
      env: COMPONENT_NAME=service2

    - <<: *dev-deploy-stage
      if: branch =~ ^srv-service3- OR branch =~ ^multi- OR branch = master
      env: COMPONENT_NAME=service3

    - <<: *dev-deploy-stage
      if: branch =~ ^srv-service4- OR branch =~ ^multi- OR branch = master
      env: COMPONENT_NAME=service4

    # Prod image
    - &prod-deploy-stage
      stage: deploy
      script:
        - COMPONENT_TYPE=srv ./ci/modified.sh || travis_terminate
        - BUILD_ENV=dev ./ci/deploy.sh
      if: branch = master
      env: COMPONENT_NAME=service1

    - <<: *prod-deploy-stage
      env: COMPONENT_NAME=service2

    - <<: *prod-deploy-stage
      env: COMPONENT_NAME=service3

    - <<: *prod-deploy-stage
      env: COMPONENT_NAME=service4
