conditions: v1

language: go

go: 1.10.x

install: skip

env:
  global:
      - MULTI_SERVICE="^multi\-"

jobs:
  include:
    # Run tests
    - &test-stage
      stage: test
      env: SERVICE="^service1\-" APP_ENV=test TEST_SUITE=php_functional_1
      if: branch =~ env(SERVICE) OR branch =~ env(MULTI_SERVICE)
      #script: if $(./ci/modified.sh); then ./ci/test.sh; else travis_terminate; fi

    - <<: *test-stage
      env: SERVICE="^service1\-" APP_ENV=test TEST_SUITE=php_functional_2

    - <<: *test-stage
      env: SERVICE="^service2\-"

    - <<: *test-stage
      env: SERVICE="^service3\-" SOME_OTHER_VAR="whatever"

    - <<: *test-stage
      env: SERVICE="^service4" AA=1

    - <<: *test-stage
      env: SERVICE="^service4" BB=1

    # # Dev image to be used for nobob and QA
    # - &dev-deploy-stage
    #   stage: deploy
    #   env: APP_ENV=dev SERVICE="1"
    #   if: branch =~ ^env(SERVICE)\- or branch =~ ^env(MULTI_SERVICE)\-
    #   script: if $(./ci/modified.sh); then ./ci/test.sh; else travis_terminate; fi
    #   deploy:
    #     - provider: script
    #       script: ./ci/deploy.sh
    #       skip_cleanup: true
    #       on:
    #         all_branches: true

    # - <<: *dev-deploy-stage
    #   env: APP_ENV=dev SERVICE="2"

    # - <<: *dev-deploy-stage
    #   env: APP_ENV=dev SERVICE="3"

    # - <<: *dev-deploy-stage
    #   env: APP_ENV=dev SERVICE="4"



#     # Prod image
#     - stage: deploy
#       env: APP_ENV=prod CLUSTER=production
#       script: skip
#       deploy:
#         - provider: script
#           script: ./ci/deploy.sh
#           skip_cleanup: true
#           on:
#             branch: master
# 1